### ISSUE TITLE
Proposal: Support Nodejs 10.x

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2chatops#109]
Nodejs 10.x was released in [April 2018](https://github.com/nodejs/Release#release-schedule).

We currently support Nodejs 6.x.

I propose we skip 8.x, and go straight to 10.x support.

Required:
 - [x] Test st2chatops with Nodejs 10.x
 - [x] Update CI to use 10.x
 - [x] Figure out upgrade path for existing users
 - [x] Update packaging scripts to install 10.x
 - [x] Update documentation to use 10.x.

**Comment by arm4b** [comment]
cc @enykeev @christopherjbaker as someone experienced with `.js`, - let us know if there could be any possible roadblocks with Node 10 from your point of view.

This will involve both https://github.com/StackStorm/st2chatops and https://github.com/stackstorm/hubot-stackstorm repos.

**Comment by christopherjbaker** [comment]
They do schedule the LTS so you can skip every other one. v10 will become LTS in October and stay until sleep 2020, but there's no reason to not use it now. TBH, with almost every node upgrade I've done, you can just switch and don't have to change anything; all my projects are on v10. I switched the day it came out.

The exception to this is when you are using native modules, as this apis often break between versions. I don't imagine you are directly, but there could be some in your dependency tree. By this point, any maintained libraries will probably be updated for 10, so this probably won't be an issue. There might not be prebuilt binaries available for those packages yet, but that just means you'll need a few extra dependents (mainly python) and it will take a bit longer.

I would just give it a shot, especially if you have tests. Make sure to delete old node_modules and package-lock.json (if you were on 6, you might not have this), and reinstall. This would be a good opportunity to make sure all your dependencies are up to date too.

**Comment by LindsayHill** [comment]
That's good to hear that upgrades are generally smooth. The thinking behind going direct to v10 was due to it going to LTS soonish anyway. Due to the way the repos work, switching from v6 to v8 to v10 repos is a bit of a pain (more hoops to jump through). So it's better if we can just skip v8.

There's quite a few dependencies that need updating here too. This will be a good excuse to do a big sweep through and update a whole lot of them

**Comment by blag** [comment]
Closed with #116.
