### ISSUE TITLE
CI jobs are succeeding despite errors in them

### ISSUE THREAD

**Issue by punkrokk** [StackStorm/st2chatops#143]
st2chatops `build` and `test` jobs showing green :heavy_check_mark: status, ignoring error return codes during the script executions.

----

* Set all st2chatops builds to fail upon errors.
* Ensure not a breaking change

- [x] el7
- [x] el6
- [x] bionic
- [x] xenial 
- [x] trusty

**Comment by arm4b** [comment]
Just updated the issue with more accurate description.

Also, looks like we actually had this bug for a long time: https://github.com/StackStorm/st2chatops/issues/48

**Comment by arm4b** [comment]
Duplicate of #48
