### ISSUE TITLE
update slack-hubot package to v4.10.0

### ISSUE THREAD

**Issue by lopf** [StackStorm/st2chatops#177]
Slack is retiring the _rtm.start_ endpoint in September 2022: https://api.slack.com/changelog/2021-10-rtm-start-to-stop

The latest hubot-slack package ([v4.10.0](https://github.com/slackapi/hubot-slack/releases/tag/v4.10.0)) defaults to the new _rtm.connect_ method.

**Comment by NikonNLG** [comment]
@armab It's already September. After Sep 27 st2chatops can stop work

**Comment by arm4b** [comment]
Thanks for the heads up @NikonNLG! Left the review there. 

We're definitely missing someone with nodejs/js knowledge to maintain the `st2chatops`.
