### ISSUE TITLE
when running the startup script, env variables don't get configured

### ISSUE THREAD

**Issue by sebgoa** [StackStorm/st2chatops#20]
When running the startup script, it looks like the mount that is supposed to set the en variable does not get used properly.

container dies:

```
$ docker logs stackstorm-hubot
Must provide HUBOT_ADAPTER ENV variable to start.
See README.md for more information
```

**Comment by sebgoa** [comment]
looks like the stackstorm/hubot:latest image does not have the latest bin/hubot script which sources /app/st2chatops.env

Can you push a latest image ?

thanks

**Comment by emedvedev** [comment]
Pushed, closing the issue. Thanks!

**Comment by tdally** [comment]
I just installed using the startup script and I am getting the same error:

**Comment by arm4b** [comment]
@tdally What is the startup script are you referring to?
For chatops, you need to configure `st2chatops.env` located in `/opt/stackstorm/chatops/`, like specify settings for adapter used.
