### ISSUE TITLE
st2chatops should not assume existence of st2 user

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2chatops#31]
It should be possible to install st2chatops on a node that does not have `st2` user and group. This assumption comes from the fact that `st2` package is always installed and that may not always be true.

Likely need to do https://github.com/StackStorm/st2-packages/blob/master/packages/st2/debian/preinst#L34 here as well.

**Comment by paul-mulvihill** [comment]
I've just hit this as well when doing a HA setup, where chatops is not on the same node as the rest of st2. I had to manually create the st2 user and after that st2chatops started up and my slack bot came online. Just need to make sure it is there or create it during the install.
