### ISSUE TITLE
external-scripts.json should be listed as a conffile

### ISSUE THREAD

**Issue by jjm** [StackStorm/st2chatops#53]
Every time I upgrade st2chatops I need to edit `external-scripts.json` and re-add our hubot module, it really should be listed as an conffile so that the user has the option to preserve any local changes.

**Comment by jjm** [comment]
It's the following in the spec file to do the same on rpm systems:

```
%config(noreplace) /opt/stackstorm/chatops/st2chatops.env
%config(noreplace) /opt/stackstorm/chatops/external-scripts.json
```

I can add this to the PR if you want.

**Comment by arm4b** [comment]
:+1:
