### ISSUE TITLE
Remove chatops command

### ISSUE THREAD

**Issue by roberterdin** [StackStorm/st2chatops#58]
How do you unregister a chatops command? I registered the run remote command from the [documentation](https://docs.stackstorm.com/chatops/chatops.html#adding-new-chatops-commands), which works. However, unregistering does either not work or the process is not straightforward. Removing the file from the `my-chatops/aliases` and running `st2ctl reload --register-all` does not work. `service st2chatops restart` doesn't help either. 
Is this a bug or just not documented?

**Edit:**
I figured out that 
`st2 run packs.uninstall packs=my-chatops`
`service st2chatops restart` 
does the trick. Is there a way to remove single commands from a pack without removing the whole thing?

**Comment by LindsayHill** [comment]
You can remove individual aliases with `st2 action-alias delete`
