### ISSUE TITLE
st2chatops cannot be installed without st2 repo on a separate instance

### ISSUE THREAD

**Issue by humblearner** [StackStorm/st2chatops#67]
We allow installation of st2chatops on a separate instance : https://github.com/StackStorm/st2chatops/blob/master/st2chatops.env#L23.
However, it depends on st2 package as st2 creates `/var/log/st2/`. 

Discovered here : https://github.com/StackStorm/ansible-st2/pull/125#discussion_r105504625

```
RUNNING HANDLER [st2chatops : restart st2chatops] ******************************
fatal: [centos6]: FAILED! => {"changed": false, "failed": true, "msg": "touch: cannot touch `/var/log/st2/st2chatops.log': No such file or directory\nrunuser: group st2 does not exist\n"}
```

---

Saying that, `st2chatops` package should try to create `/var/log/st2/` dirs as well as `st2` user if it doesn't exists yet.

**Comment by arm4b** [comment]
It's actually the same (duplicate) as 1 yr. ago reported Issue: https://github.com/StackStorm/st2chatops/issues/31

**Comment by LindsayHill** [comment]
Resolved by https://github.com/StackStorm/st2chatops/pull/114
