### ISSUE TITLE
Chatops bot does not send message to hip chat room

### ISSUE THREAD

**Issue by nikunjvirani** [StackStorm/st2chatops#72]
I am able to communicate with bot on a private message but not able to have bot communicate to hip chat room. Debug log shows that message is being sent but does not show up.

**Comment by Mierdin** [comment]
Hello - have you checked `/var/log/st2/st2chatops.log` for any interesting messages?

**Comment by arm4b** [comment]
From the #community Slack:

in a 1-1 chat, I can type `help`, and it works as expected.  If I do the same in a channel (`@myBotName !help`), I see the message was received in the log
```[Mon Jun 12 2017 14:18:20 GMT-0700 (PDT)] DEBUG Message 'myBotName:  !help' matched regex //^\s*[@]?(?:myBotName[:,]?|![:,]?)\s*(?:([\s\S]+?)$)/i/; listener.options = { id: null }
[Mon Jun 12 2017 14:18:20 GMT-0700 (PDT)] DEBUG Executing listener callback for Message 'myBotName:  !help'
[Mon Jun 12 2017 14:18:39 GMT-0700 (PDT)] DEBUG  OUT > <r/>
```

So there is regex match and so on.

----
We need to setup testing Hipchat account and debug it by ourselves, verify if reproducible.

Could be something that changed with the upstream https://github.com/hipchat/hubot-hipchat and Hipchat API itself that wasn't included in https://github.com/stackstorm/hubot-stackstorm.

**Comment by arm4b** [comment]
I just installed `stable` (`2.2.1`) StackStorm on `Ubuntu16` with demo [`curl|bash` installer](https://docs.stackstorm.com/install/index.html).
Then I created a new `armab.hipchat.com` organization.
After that, I created a new hipchat user `@hubot`. Being logged in as @hubot in Hipchat, I obtained `HUBOT_HIPCHAT_JID` from https://armab.hipchat.com/account/xmpp and set it in `st2chatops.env`, as well as a password for `@hubot` user.

`st2chatops.env` is the folllowing:
```sh
export ST2_HOSTNAME="${ST2_HOSTNAME:-localhost}"
export NODE_TLS_REJECT_UNAUTHORIZED=0
export EXPRESS_PORT=8081
export HUBOT_LOG_LEVEL=debug

export HUBOT_NAME=hubot
export HUBOT_ALIAS='!'

######################################################################
# StackStorm settings

# StackStorm API endpoint.
export ST2_API="${ST2_API:-https://${ST2_HOSTNAME}/api}"

# StackStorm API key
export ST2_API_KEY=********************************

# Public URL of StackStorm instance: used it to offer links to execution details in a chat.
export ST2_WEBUI_URL=https://${ST2_HOSTNAME}

# HipChat settings (https://github.com/hipchat/hubot-hipchat):
#
export HUBOT_ADAPTER=hipchat
export HUBOT_HIPCHAT_JID=457227_5049438@chat.hipchat.com
export HUBOT_HIPCHAT_PASSWORD=*********

```

After `sudo service st2chaops restart` `@hubot` user joined the room and could respond to Hubot native commands like `!help`, as well as StackStorm commands like `!pack show github`.

![](https://i.imgur.com/WnchJTS.png)

Here is the full hipchat log with masked secrets: https://gist.github.com/armab/2ff1bd5774191e8ebbc0922e8c7fbf10

----

So I couldn't reproduce it so far.
@nikunjvirani Please compare the logic/logs/configs described above with yours and let me know if you have any ideas and more details to share. I would try to go with the most default working installation first and then try any customizations.
Additionally, make sure you don't log in with the same account as bot.

**Comment by arm4b** [comment]
Apart of that, I could find related issues: 
- https://github.com/hubotio/hubot/issues/651
- https://github.com/hipchat/hubot-hipchat/issues/163

Please take a look, they're mostly caused by Hipchat configuration.
Additionally, you didn't mention that: by any chance, are you using `your-org-name.hipchat.com` or a self-hosted server?

**Comment by mickmcgrath13** [comment]
@armab Thank you for looking into this and for referencing the other issues.  We are running on our own host, and we do now have it working!  The key factor was:
https://github.com/hubotio/hubot/issues/651#issuecomment-72573648

```
If you are using the self hosted version of hipchat make sure you

$ export HUBOT_HIPCHAT_XMPP_DOMAIN=btf.hipchat.com

This resolved the issue for me.
```
This issue can be closed, now, as @nikunjvirani and I are on the same team :)

Thank you, again, for looking into this!

**Comment by arm4b** [comment]
@mickmcgrath13 @nikunjvirani Cool! Glad it worked.

BTW, you can contribute a Pull Request for the following: https://github.com/StackStorm/st2chatops/blob/f74610ae18014a48c0da409b1a36f19b123b053d/st2chatops.env#L59 line comment to make it more explicit/clear.

That might help someone else in the future ;)
