### ISSUE TITLE
st2chatops self check script does not complete on u16

### ISSUE THREAD

**Issue by m4dcoder** [StackStorm/st2chatops#81]
On u16, the self check script https://github.com/StackStorm/st2chatops/blob/master/scripts/self-check.sh fails at step 10 with error `chatops.post_message hasn't been received`. st2chatops is running and I was able to run `!help` and `!pack install ...`

**Comment by humblearner** [comment]
The reason for that is that U16 doesn't have `st2chatops` logs in `/var/log/st2/st2chatops.log`: https://github.com/StackStorm/st2chatops/blob/master/scripts/self-check.sh#L205 instead, we can get the logs from `journalctl --unit=st2chatops`

**Comment by m4dcoder** [comment]
Yeah, I figured. The self check script should probably figure out it's on u16 and use journalctl.  Anyway, it's not a blocker for v2.4 IMO but we should fix.

**Comment by jinpingh** [comment]
Tested on `u16` with version `st2 3.1dev (8cffe7f), on Python 2.7.12` and issue was fixed.  See  https://github.com/StackStorm/st2chatops/commit/c590deffdc11a325352c0c04a4d2635f9e3325c4#diff-71df063722838fe48788cdba63333158.
