### ISSUE TITLE
INFO Slack client closed, waiting for reconnect

### ISSUE THREAD

**Issue by lshahar** [StackStorm/st2chatops#86]
Hello,
We found that st2chatops is have random disconnections from slack,
The expected behavior that the hubot/stackstorm will try to reconnect slack.
At logs we found line 'INFO Slack client closed, waiting for reconnect' but it's not trying to reconnect.

**Comment by LindsayHill** [comment]
Which version are you using? 

Recently released StackStorm 2.4 includes an updated hubot-slack module, which improves some of this behavior

**Comment by shreyas-shinde** [comment]
slack 4.4.0 version fixes related issue. so st2chatops should use that version. https://github.com/slackapi/hubot-slack/pull/420

**Comment by LindsayHill** [comment]
https://github.com/StackStorm/st2chatops/pull/116 updates hubot-slack to 4.5.5
